### ISSUE TITLE
How to load videos only from particular channels

### ISSUE THREAD

**Issue by NektariosFifes** [productioncoder/youtube-react#9]
Hello i am relatively new to react. After viewing the code i struggle to understand how the videos property is filled in the video grid. Could you please point me to correct direction? How can i make the api call  return certain videos only from certain channels. Also can i load private videos on my channel on youtube? Thanks in advance.

**Comment by productioncoder** [comment]
Hi,

the videos are loaded by hitting the `/videos` endpoint on the [Youtube Data API v3](https://developers.google.com/youtube/v3/docs/videos/list).

There is a more in depth description on how to do the following two posts on my blog
* [Part 22](https://productioncoder.com/build-youtube-in-react-part-22/)
* [Part 23](https://productioncoder.com/build-youtube-in-react-part-22/)

You can search for videos on a specific channel by using the `/search` endpoint of the [Youtube Data API v3](https://developers.google.com/youtube/v3/docs/search/list)

I think it should also be possible to load unlisted videos (note that these are not private but they will not show up in the search). As far as private videos are concerned, you'd probably need to be logged in to see embed them.

Best,

Jan
